[package]
name = "test"
version = "0.0.1"

[dependencies]
Sui = { git = "https://github.com/MystenLabs/sui.git", subdir = "crates/sui-framework", rev = "devnet" }
move_lock = { local = "../movectf" }

[addresses]
ctf =  "0x0"
sui =  "0000000000000000000000000000000000000002"
